(* re-exported from App_bsky_shared_1 *)

type post_view = App_bsky_shared_1.post_view
let post_view_of_yojson = App_bsky_shared_1.post_view_of_yojson
let post_view_to_yojson = App_bsky_shared_1.post_view_to_yojson

type viewer_state = App_bsky_shared_1.feed_viewer_state
let viewer_state_of_yojson = App_bsky_shared_1.feed_viewer_state_of_yojson
let viewer_state_to_yojson = App_bsky_shared_1.feed_viewer_state_to_yojson

type thread_context = App_bsky_shared_1.thread_context
let thread_context_of_yojson = App_bsky_shared_1.thread_context_of_yojson
let thread_context_to_yojson = App_bsky_shared_1.thread_context_to_yojson

type feed_view_post = App_bsky_shared_1.feed_view_post
let feed_view_post_of_yojson = App_bsky_shared_1.feed_view_post_of_yojson
let feed_view_post_to_yojson = App_bsky_shared_1.feed_view_post_to_yojson

type reply_ref = App_bsky_shared_1.reply_ref
let reply_ref_of_yojson = App_bsky_shared_1.reply_ref_of_yojson
let reply_ref_to_yojson = App_bsky_shared_1.reply_ref_to_yojson

type reason_repost = App_bsky_shared_1.reason_repost
let reason_repost_of_yojson = App_bsky_shared_1.reason_repost_of_yojson
let reason_repost_to_yojson = App_bsky_shared_1.reason_repost_to_yojson

type reason_pin = App_bsky_shared_1.reason_pin
let reason_pin_of_yojson = App_bsky_shared_1.reason_pin_of_yojson
let reason_pin_to_yojson = App_bsky_shared_1.reason_pin_to_yojson

type thread_view_post = App_bsky_shared_1.thread_view_post
let thread_view_post_of_yojson = App_bsky_shared_1.thread_view_post_of_yojson
let thread_view_post_to_yojson = App_bsky_shared_1.thread_view_post_to_yojson

type not_found_post = App_bsky_shared_1.not_found_post
let not_found_post_of_yojson = App_bsky_shared_1.not_found_post_of_yojson
let not_found_post_to_yojson = App_bsky_shared_1.not_found_post_to_yojson

type blocked_post = App_bsky_shared_1.blocked_post
let blocked_post_of_yojson = App_bsky_shared_1.blocked_post_of_yojson
let blocked_post_to_yojson = App_bsky_shared_1.blocked_post_to_yojson

type blocked_author = App_bsky_shared_1.blocked_author
let blocked_author_of_yojson = App_bsky_shared_1.blocked_author_of_yojson
let blocked_author_to_yojson = App_bsky_shared_1.blocked_author_to_yojson

type generator_view = App_bsky_shared_1.generator_view
let generator_view_of_yojson = App_bsky_shared_1.generator_view_of_yojson
let generator_view_to_yojson = App_bsky_shared_1.generator_view_to_yojson

type generator_viewer_state = App_bsky_shared_1.generator_viewer_state
let generator_viewer_state_of_yojson = App_bsky_shared_1.generator_viewer_state_of_yojson
let generator_viewer_state_to_yojson = App_bsky_shared_1.generator_viewer_state_to_yojson

type skeleton_feed_post = App_bsky_shared_1.skeleton_feed_post
let skeleton_feed_post_of_yojson = App_bsky_shared_1.skeleton_feed_post_of_yojson
let skeleton_feed_post_to_yojson = App_bsky_shared_1.skeleton_feed_post_to_yojson

type skeleton_reason_repost = App_bsky_shared_1.skeleton_reason_repost
let skeleton_reason_repost_of_yojson = App_bsky_shared_1.skeleton_reason_repost_of_yojson
let skeleton_reason_repost_to_yojson = App_bsky_shared_1.skeleton_reason_repost_to_yojson

type skeleton_reason_pin = App_bsky_shared_1.skeleton_reason_pin
let skeleton_reason_pin_of_yojson = App_bsky_shared_1.skeleton_reason_pin_of_yojson
let skeleton_reason_pin_to_yojson = App_bsky_shared_1.skeleton_reason_pin_to_yojson

type threadgate_view = App_bsky_shared_1.threadgate_view
let threadgate_view_of_yojson = App_bsky_shared_1.threadgate_view_of_yojson
let threadgate_view_to_yojson = App_bsky_shared_1.threadgate_view_to_yojson

type interaction = App_bsky_shared_1.interaction
let interaction_of_yojson = App_bsky_shared_1.interaction_of_yojson
let interaction_to_yojson = App_bsky_shared_1.interaction_to_yojson

let request_less = App_bsky_shared_1.request_less

let request_more = App_bsky_shared_1.request_more

let clickthrough_item = App_bsky_shared_1.clickthrough_item

let clickthrough_author = App_bsky_shared_1.clickthrough_author

let clickthrough_reposter = App_bsky_shared_1.clickthrough_reposter

let clickthrough_embed = App_bsky_shared_1.clickthrough_embed

let content_mode_unspecified = App_bsky_shared_1.content_mode_unspecified

let content_mode_video = App_bsky_shared_1.content_mode_video

let interaction_seen = App_bsky_shared_1.interaction_seen

let interaction_like = App_bsky_shared_1.interaction_like

let interaction_repost = App_bsky_shared_1.interaction_repost

let interaction_reply = App_bsky_shared_1.interaction_reply

let interaction_quote = App_bsky_shared_1.interaction_quote

let interaction_share = App_bsky_shared_1.interaction_share

